spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mi_basedatos_2
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    defer-datasource-initialization: false
    hibernate:
      #ddl-auto: none         #No crea ni actualiza tablas automáticamente. Asume que la BD ya está creada.
      #ddl-auto: create       #Crea las tablas cada vez que arranca la aplicación. #⚠️ Borra tolo que hubiera antes.
      #ddl-auto: create-drop  #Igual que create, pero además borra las tablas al apagar la aplicación.
      ddl-auto: update        #Crea las tablas si no existen y actualiza el esquema sin borrar datos. Es la opción más cómoda mientras desarrollas.
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true
  # Si quieres que Spring Boot ejecute automáticamente schema.sql y data.sql al arrancar, la propiedad clave es esta:
  # jecutar siempre schema.sql y data.sql
  # Si tienes JPA activado (y tú lo tienes), debes añadir: spring.jpa.defer-datasource-initialization: true
  # Esto permite que los scripts SQL se ejecuten antes de que Hibernate empiece a trabajar, evitando que Hibernate bloquee la inicialización.
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
    root: info

server:
  port: 8080

