spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mi_basedatos_2
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
    root: info

server:
  port: 8080
